#pragma once

#include <optional>

#include "eckit/exception/Exceptions.h"
#include "eckit/log/Log.h"

#include "metkit/config/LibMetkit.h"


namespace metkit::mars2grib::backend::deductions {

// TODO MIVAL: These tables should be generated by a python script
// from eccodes definitions at build time because they may change over time
// There is no known (to the author) automatic way to get these tables from eccodes directly
// or to set these values in grib messages via string or via eccodes API.

// eccodes codes table 1.3
enum class ProductionStatusOfProcessedData : long {
    OperationalProducts                    = 0,
    OperationalTestProducts                = 1,
    ResearchProducts                       = 2,
    ReanalysisProducts                     = 3,
    TiggeOperational                       = 4,
    TiggeTest                              = 5,
    S2SOperationalProducts                 = 6,
    S2STestProducts                        = 7,
    UerraOperational                       = 8,
    UerraTest                              = 9,
    CopernicusRegionalReanalysis           = 10,  // CARRA / CERRA
    CopernicusRegionalReanalysisTest       = 11,  // CARRA / CERRA
    DestinationEarth                       = 12,
    DestinationEarthTest                   = 13,
    Missing                                = 255
};

constexpr ProductionStatusOfProcessedData AllProductionStatusOfProcessedData[] = {
    ProductionStatusOfProcessedData::OperationalProducts,
    ProductionStatusOfProcessedData::OperationalTestProducts,
    ProductionStatusOfProcessedData::ResearchProducts,
    ProductionStatusOfProcessedData::ReanalysisProducts,
    ProductionStatusOfProcessedData::TiggeOperational,
    ProductionStatusOfProcessedData::TiggeTest,
    ProductionStatusOfProcessedData::S2SOperationalProducts,
    ProductionStatusOfProcessedData::S2STestProducts,
    ProductionStatusOfProcessedData::UerraOperational,
    ProductionStatusOfProcessedData::UerraTest,
    ProductionStatusOfProcessedData::CopernicusRegionalReanalysis,
    ProductionStatusOfProcessedData::CopernicusRegionalReanalysisTest,
    ProductionStatusOfProcessedData::DestinationEarth,
    ProductionStatusOfProcessedData::DestinationEarthTest,
    ProductionStatusOfProcessedData::Missing
};

constexpr inline bool isValidProductionStatusOfProcessedData( long x ) {
    bool match = false;
    for ( const auto& t : AllProductionStatusOfProcessedData ){
        if ( long(t) == v ){
            match = true;
            break;
        };
    }
    return match;
};


// TODO MIVAL: this logic at the moment is very weak, as it does not cover all cases
// need interaction with DGOV team to improve/define this mapping

// grib2 section 1 octet 20
template<class MarsDict_t, class ParDict_t>
std::optional<ProductionStatusOfProcessedData> productionStatusOfProcessed(
    const MarsDict_t& mars, cost ParDict_t& par){

    // Get mars type from dictionary
    auto marsClass = get_or_throw<ConceptException,std::string>( mars, "class",
        [](){
            return "`class` is required in mars dictionary to deduce `productionStatusOfProcessedData`";
        },
        Here()
    );

    // Deduce typeOfProcessedData from mars type
    if ( marsClass == "d1" ) {
        return {ProductionStatusOfProcessedData::DestinationEarth};
    }
    else {
        // Logging
        LOG_DEBUG_LIB(LibMetkit)
              << "WARNNG: Unable to deduce `productionStatusOfProcessedData` from mars `class`=" << marsClass
              <<  ", at: " << Here()
              <<  ", fallback to productionStatusOfProcessedData=MISSING"
              << std::endl;
        return {ProductionStatusOfProcessedData::Missing};
    };


};


} // namespace metkit::mars2grib::backend::deductions