#pragma once

#include <optional>
#include <array>
#include <string>
#include <string_view>
#include <algorithm>


#include "eckit/exception/Exceptions.h"
#include "eckit/log/Log.h"

#include "metkit/config/LibMetkit.h"


namespace metkit::mars2grib::backend::deductions {

// TODO MIVAL: These tables should be generated by a python script
// from eccodes definitions at build time because they may change over time
// There is no known (to the author) automatic way to get these tables from eccodes directly
// or to set these values in grib messages via string or via eccodes API.
enum class SignificanceOfReferenceTime : uint8_t {
    Analysis              = 0,
    ForecastStart         = 1,
    ForecastVerification  = 2,
    ObservationTime       = 3,
    LocalTime             = 4,
    SimulationStart       = 5,
    Missing               = 255
};



// grib2 section 1 octet 12 for significance of reference time (code Table 1.2)
template<class MarsDict_t, class ParDict_t>
std::optional<SignificanceOfReferenceTime> significanceOfReferenceTime(
    const MarsDict_t& mars, const ParDict_t& par){

    // Get the mars.type
    auto marsType = get_or_throw<std::string>(
        mars, "type",
        [](){
            return "`type` is required in mars dictionary to deduce `significanceOfReferenceTime`";
        },
        Here() );

    constexpr std::array<std::string_view, 19> analysisTypes = {{
        "an", "ia", "oi", "3v", "4v", "3g", "4g", "ea", "4i",
        "pa", "tpa", "ga", "gai", "ai", "af", "ab", "oai",
        "ga", "gai"
    }};

    constexpr std::array<std::string_view, 33> forecastTypes = {{
        "fc", "cf", "pf", "cm", "fp", "em", "es", "fa",
        "efi", "efic", "bf", "cd", "me", "wem", "wes", "cr",
        "ses", "taem", "taes", "sg", "sf", "if",
        "fcmean", "fcmax", "fcmin", "fcstdev",
        "ssd", "tf", "bf", "cd", "hcmean", "s3", "si"
    }};

    if (std::any_of(analysisTypes.begin(), analysisTypes.end(),
                [&marsType](auto v){ return marsType == v; }))
    return TimeReference::Analysis;

    if (std::any_of(forecastTypes.begin(), forecastTypes.end(),
                [&marsType](auto v){ return marsType == v; }))
    return TimeReference::ForecastStart;

    throw std::runtime_error(
        std::string("Unhandled marsType: ") + std::string(marsType)
    );


    };

} // namespace metkit::mars2grib::backend::deductions