#pragma once

#include <optional>
#include <cstdint>

#include "eckit/exception/Exceptions.h"
#include "eckit/log/Log.h"

#include "metkit/config/LibMetkit.h"


namespace metkit::mars2grib::backend::deductions {

// TODO MIVAL: These tables should be generated by a python script
// from eccodes definitions at build time because they may change over time
// There is no known (to the author) automatic way to get these tables from eccodes directly
// or to set these values in grib messages via string or via eccodes API.

// eccodes codes table 4.6
enum class typeOfEnsembleForecast : long {
    UnperturbedHighResControl           = 0,
    UnperturbedLowResControl            = 1,
    NegativelyPerturbed                 = 2,
    PositivelyPerturbed                 = 3,
    MultiModel                          = 4,
    Unperturbed                         = 5,
    Perturbed                           = 6,
    InitialConditionsPerturbations      = 7,
    ModelPhysicsPerturbations           = 8,
    InitialAndModelPhysicsPerturbations = 9,
    Missing                             = 255
};


// TODO MIVAL: this logic at the moment is very weak, as it does not cover all cases
// need interaction with DGOV team to improve/define this mapping

template<class MarsDict_t, class ParDict_t>
typeOfEnsembleForecast productionStatusOfProcessed(
    const MarsDict_t& mars, cost ParDict_t& par){

    // Get mars type from dictionary
    std::string marsType = get_or_throw<ConceptException,std::string>( mars, "type",
        [](){
            return "`type` is required in mars dictionary to deduce `typeOfEnsembleForecast`";
        },
        Here()
    );

    if (  marsType == "cf" ) {
        return typeOfEnsembleForecast::Unperturbed;
    }
    else if ( marsType == "pf" ) {
        return typeOfEnsembleForecast::Perturbed;
    }
    else {
        throw ConceptException(
            "`type` value '" + marsType + "' is not mapped to any known `typeOfEnsembleForecast`",
            Here()
        );
    }

};


} // namespace metkit::mars2grib::backend::deductions