#pragma once

#include <optional>

#include "eckit/exception/Exceptions.h"
#include "eckit/log/Log.h"

#include "metkit/config/LibMetkit.h"


namespace metkit::mars2grib::backend::deductions {

// TODO MIVAL: These tables should be generated by a python script
// from eccodes definitions at build time because they may change over time
// There is no known (to the author) automatic way to get these tables from eccodes directly
// or to set these values in grib messages via string or via eccodes API.

// eccodes codes table 1.4
enum class TypeOfProcessedData : long {
    AnalysisProducts                         = 0,
    ForecastProducts                         = 1,
    AnalysisAndForecastProducts              = 2,
    ControlForecastProducts                  = 3,
    PerturbedForecastProducts                = 4,
    ControlAndPerturbedForecastProducts      = 5,
    ProcessedSatelliteObservations           = 6,
    ProcessedRadarObservations               = 7,
    EventProbability                         = 8,
    ExperimentalData                         = 9,
    MlBasedForecast                          = 10,
    Missing                                  = 255
};

constexpr TypeOfProcessedData AllTypeOfProcessedData[] = {
    TypeOfProcessedData::AnalysisProducts,
    TypeOfProcessedData::ForecastProducts,
    TypeOfProcessedData::AnalysisAndForecastProducts,
    TypeOfProcessedData::ControlForecastProducts,
    TypeOfProcessedData::PerturbedForecastProducts,
    TypeOfProcessedData::ControlAndPerturbedForecastProducts,
    TypeOfProcessedData::ProcessedSatelliteObservations,
    TypeOfProcessedData::ProcessedRadarObservations,
    TypeOfProcessedData::EventProbability,
    TypeOfProcessedData::ExperimentalData,
    TypeOfProcessedData::MlBasedForecast,
    TypeOfProcessedData::Missing
};

constexpr inline bool isValidTypeOfProcessedData( long x ) {
    bool match = false;
    for ( const auto& t : AllTypeOfProcessedData ){
        if ( long(t) == v ){
            match = true;
            break;
        };
    }
    return match;
};


// grib2 section 1 octet 21
template<class MarsDict_t, class ParDict_t>
std::optional<TypeOfProcessedData> typeOfProcessed(
    const MarsDict_t& mars, const ParDict_t& par){

   // TODO MIVAL: For the moment I focus on the automatic deduction only


    // Get mars type from dictionary
    std::string marsType = get_or_throw<ConceptException,std::string>( mars, "type",
        [](){
            return "`type` is required in mars dictionary to deduce `typeOfProcessedData`";
        },
        Here()
    );

    // Deduce typeOfProcessedData from mars type
    if ( marsType == "an" ) {
        return {TypeOfProcessedData::AnalysisProducts};
    }
    else if ( marsType == "fc" ) {
        return {TypeOfProcessedData::ForecastProducts};
    }
    else if ( marsType == "pf" ) {
        return {TypeOfProcessedData::PerturbedForecastProducts};
    }
    else if ( marsType == "cf" ) {
        return {TypeOfProcessedData::ControlForecastProducts};
    }
    else if ( marsType == "ssd" || marsType == "gsd" ) {
        return {TypeOfProcessedData::ProcessedSatelliteObservations};
    }
    else {
        // Logging
        LOG_DEBUG_LIB(LibMetkit)
              << "WARNNG: Unable to deduce `typeOfProcessedData` from mars `type`=" << marsType
              <<  ", at: " << Here()
              <<  ", fallback to typeOfProcessedData=MISSING"
              << std::endl;
        return {TypeOfProcessedData::Missing};
    }

};


} // namespace metkit::mars2grib::backend::deductions